version: '2'
services: 
  nginx:
    image: nginx:alpine
    container_name: manager_api_nginx
    ports: 
      - "8000:8000"
    volumes: 
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on: 
      - web
      
  web:
    build: .
    container_name: manager_api
    volumes: 
      - ./src:/src
    env_file: 
      - ./.env
    expose: 
      - "8000"