# Generated by Django 3.0.2 on 2020-05-19 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='websiteads',
            name='adsizes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdSizes'),
        ),
        migrations.AddField(
            model_name='websiteads',
            name='websites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Websites'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactions',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionrunningsum',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionsum_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionrunningsum',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionsum_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisherreport',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Websites'),
        ),
        migrations.AddField(
            model_name='category',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AddField(
            model_name='campaignreport',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Campaign'),
        ),
        migrations.AddField(
            model_name='campaignrelations',
            name='adgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdGroups'),
        ),
        migrations.AddField(
            model_name='campaignrelations',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ads'),
        ),
        migrations.AddField(
            model_name='campaignrelations',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Campaign'),
        ),
        migrations.AddField(
            model_name='campaignrelations',
            name='campaign_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdCampaignDetails'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='adgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdGroups'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adservesite',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Campaign'),
        ),
        migrations.AddField(
            model_name='adservesite',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Websites'),
        ),
        migrations.AddField(
            model_name='ads',
            name='ad_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdGroups'),
        ),
        migrations.AddField(
            model_name='ads',
            name='ad_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdSizes'),
        ),
        migrations.AddField(
            model_name='adcampaigndetails',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Campaign'),
        ),
    ]
