# Generated by Django 3.0.2 on 2020-06-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conference_conferencetest_confownprofile_location_rating_report_speaker'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
